-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgENmjhLPabdzLXEAE
BYqgjMAb8tDk/I3LmQaWKZvcEUSgCgYIKoZIzj0DAQehRANCAASRKF4cyhraIi4I
lysOspBCYT/4erVuk3Wwa+uIQBNxmJvJXIJiZDRYHyylsKNWaKa4WA6EjQ6YSyMj
ffRdB4fE
-----END PRIVATE KEY-----